### ISSUE TITLE
Create facet: Document type = dc:type

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#144]
Ref #29 

What is the difference from `edm:type` facet?

**Comment by ggeisler** [comment]
@marlo-longley Do you mean why would we want to have both Document type and edm:type (which I suggested we label as "Media format")?

If so, because the are different ways to categorize the documents and offer users more ways to find the kind of documents they're interested in or want to filter by. Document type is a conceptual description for the document and Media format is a physical description of the media. Sometimes users want to narrow things down by type of media without having to select a particular document type, for example (or they are interested in text documents that could be multiple document types, etc.).

### Document type values
- Disc recording
- Document books
- Empty folder
- Exhibits
- Final pleas and clemency pleas
- Indictments
- Judgments, dissenting opinions, and sentences
- Lists, indices, and miscellaneous
- Minutes of Tribunal meetings
- Official commission transcripts
- Official Court transcripts
- Rules, rulings, and orders
- Statements and speeches
- Trial briefs

### Media format values
- Images
- Text
- Sound
- Moving image

**Comment by jcoyne** [comment]
@ggeisler the question is "where in the EAD do we find the data for each of these fields?"

**Comment by ggeisler** [comment]
Okay, I guess that is a @laurensorensen question then.

The document type values do match up to the new series organization Lauren has worked on. But they are also `dc:type` values, I believe. At they are in Lauren's original spreadsheet. But I don't know anything about what goes on in ASpace and how things go from there to the EAD.

**Comment by marlo-longley** [comment]
@ggeisler thanks for clarifying with that list of values, definitely very helpful.

**Comment by marlo-longley** [comment]
Should we index the series name for each of its children as this value to facet on?
This sheet could help clarify where in the EAD these dc fields ended up
https://docs.google.com/spreadsheets/d/1Xz0hq28tyhESPTAcpowhlhw8JHNUManDWjP3hXZDkPg/edit#gid=185071693

**Comment by thatbudakguy** [comment]
current questions:
- is this value also accessible on child nodes themselves (rather than just on the series?)
- if so, is it reliable and defined on all children?

if yes to both, use that value (whatever it is) and not the series name.

**Comment by marlo-longley** [comment]
Closing in favor of clearer tickets.
