### ISSUE TITLE
Index language at component level

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#253]
[See crosswalk sheet "Arclight" ](https://docs.google.com/spreadsheets/d/1a_doAL669TXXzadv3UC07oOAv4jS7cVCsE4wfgqPag0/edit#gid=330042512)

The xpath at the component level is: `/controlaccess/function`. Example component-level EAD:

```xml
<c>
....
<controlaccess>
    <function source="lcsh">English language</function>
    <function source="lcsh">German language</function>
  </controlaccess>
</c>
```

These are technically LCSH subjects and therefore include the word "language".

In discussion pasted from #217, @ggeisler noted that he would prefer to only display the word "English" in the UI, rather than "English language" for example. Given this, there is a question of whether we should chop off the word "language" at index time, or display time, and that should be resolved in this ticket as a technical question.

> Are you suggesting that for an item with multiple languages we display them like:
> 
> Language: English language, German language, French language
> 
> If so, I'm not sure that is a good idea. Maybe we should store them that way in the EAD if you think it's important to use the LC Subject Heading entry terminology, but that's a lot of unnecessary redundancy for the user (and will increase UI space needed in places that likely should be as compact as possible), who very likely doesn't really know or care about LC Subject Headings.
> 
> So if we do store the values as "English language" I suggest we still display them as simply "English", etc.

Note that core AL indexes language from the xpath `/did/langmaterial` which is perhaps cleaner, but in order to include multiple languages, we needed to use this workaround. We need to write custom indexing for this field.

**Comment by ggeisler** [comment]
I'm sure everyone understands my comment above, but to be super clear, I have no objection at all to storing the values as "English language" in the EAD (and/or other data stores). My concern is just with the display, so if feasible it would make sense to me to just chomp off the " language" part of these values for display.

Otherwise, consider how much longer and busier this display will be (see the BORMANN result item in the mockup below that has multiple language values):

![](https://user-images.githubusercontent.com/101482/200086682-d734c4f0-ef42-4720-abd0-e67a44fba3dc.png)

And in the component metadata list, it seems odd to me to have a display like:

> **Language:** English language

rather than simply:

> **Language:** English

**Comment by marlo-longley** [comment]
Thanks @ggeisler ! I guess I didn't know from a technical perspective, if we never display the word "language" if folks think there is an argument to index it or not.

**Comment by thatbudakguy** [comment]
confirmed this is working with latest EAD data — here's some data about what we indexed:

![Screen Shot 2022-11-21 at 13 56 17](https://user-images.githubusercontent.com/4924494/203166060-205c55e1-4ad8-44bb-b937-6c8dabb1e863.png)

I liked @jcoyne's solution to remove the " language" suffix at index time.
