### ISSUE TITLE
Add Google Analytics (GA4)

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#425]

**Comment by marlo-longley** [comment]
Since we're using stimulus, should we put this on the body tag, if we added a data-controller attribute to the body tag, then we're using stimulus's hooks rather than the turbo load hook.

**Comment by marlo-longley** [comment]
- We set analytics_debug to false in config/production.rb, but our staging and prod VT servers both use this file. The solution to have analytics_debug be true for staging is to set it for staging only in Puppet.

**Comment by thatbudakguy** [comment]
noting here for posterity; cc @laurensorensen:

* VT's google analytics cannot track any viewer interactions (documents, images, video, audio) because the embedded content is in an iframe embedded from another domain, and security settings don't allow the document to interact with the inner frame. This is a built-in security feature of the web that cannot be overridden.
* There is no way to track any interaction with our video or audio players on the `sul-embed` side either. `sul-embed` collects [its own google analytics](https://analytics.google.com/analytics/web/#/report-home/a7219229w237624489p222284110), but does not log any special events for clicking play, scrubbing through the timeline, etc. this means that a pageview in `sul-embed` is equivalent to a pageview in VT; you may as well just check whether the VT page was visited instead.
* `sul-embed` _does_ collect events published by Mirador for the document viewer, including clicking the "turn page" button, which appears as `mirador/SET_CANVAS`. You can go to the "events" realtime view in `sul-embed` GA and search for a druid if you're trying to find what events were triggered on a particular purl.
* however, there is no way to know which viewer events come from VT as opposed to exhibits or any other apps that embed something. the viewer does not know the page on which it is embedded.

there is likely some work to be done in the future to improve this overall event tracking, especially in the broader context of SDR metrics, but it's out of scope for VT because it would be done in `sul-embed`, and it probably needs to be done in the context of a workcycle.
