### ISSUE TITLE
Check and release linked purls

### ISSUE THREAD

**Issue by marlo-longley** [sul-dlss/vt-arclight#50]
It seems like all (?) of the digital objects in this[ Document Books series in ASpace](http://spec-as-stage.stanford.edu:8080/resources/10208#tree::archival_object_1162656) are PURLs that have not yet been released in SDR, e.g.

https://purl.stanford.edu/rn542wb9520
https://purl.stanford.edu/kd320gs5547

**Comment by laurensorensen** [comment]
Hannah says "The PDFs that the ICJ provided to us were accessioned as dark, preservation only. We made this decision because we produced our own PDFs as part of the OCR process during SDR accessioning. Our PDFs are better than the ones they produced."

Lauren: Oh, ok! Is that for all the documents or a majority? I have to associate druids with the descriptive metadata in ASpace so looking to match them up

Hannah Frost:
  [3:48 PM](https://stanfordlib.slack.com/archives/D02U42DL4BZ/p1666046890635609)
I believe it is all, but can't swear to that. Here is the Argo link to all PDFs that are dark and therefore should not be linked to any record that would be released to ArcLight for public access
[3:48](https://stanfordlib.slack.com/archives/D02U42DL4BZ/p1666046894626659)
https://argo.stanford.edu/catalog?f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Ayc562gm1634&f%5Brights_descriptions_ssim%5D%5B%5D=dark

**Comment by laurensorensen** [comment]
I am going to follow up with Geoff who did all the accessioning and add to this ticket further

**Comment by laurensorensen** [comment]
All right, so I didn't realize before that there were two sections of documents, one section that was dark and another that was released. 
I am going to go back and re-assign item druids to the documents starting tomorrow. Could be a 2-3 day project. 

Here are the "Dark" unreleased druids: 
https://argo.stanford.edu/report?f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Ayc562gm1634&f%5Brights_descriptions_ssim%5D%5B%5D=dark

Here are the released druids that we should be using for NTA Arclight: 
https://argo.stanford.edu/report?f%5Bcontent_type_ssim%5D%5B%5D=book&f%5Bis_governed_by_ssim%5D%5B%5D=info%3Afedora%2Fdruid%3Ayc562gm1634&f%5Brights_descriptions_ssim%5D%5B%5D=world

Heads up @marlo-longley I'll be re-importing items from "Document books" sheet to ASpace once this is done. Will also add edm:type at this time too.

**Comment by laurensorensen** [comment]
Re-imported Document books this time with Format as sub-series. Discovered that the data for Format in Document books may be bad / not accurate, so I'll look again at it next week.

**Comment by laurensorensen** [comment]
Re-import is finished for Document books. Heads up there are some fields (Like alternate title) which have no data in them but WILL have data existing in other Series' uploads.
